on:
  push:
    # only trigger on branches, not on tags
    branches: "**"

env:
  AWS_REGION: us-east-1

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Configure AWS credentials to use AWS Bedrock models
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          role-to-assume: "arn:aws:iam::093575270853:role/GitHubAction-AssumeRoleWithAction"
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}

      - name: Download defect
        run: |
          wget https://github.com/DiscreteTom/defect/releases/download/v0.3.1/defect-v0.3.1-x86_64-unknown-linux-musl.zip
          unzip defect-v0.3.1-x86_64-unknown-linux-musl.zip
          rm defect-v0.3.1-x86_64-unknown-linux-musl.zip
          chmod +x defect

      - name: Review the bug
        run: |

          prompt="
          You are a coding expert.
          according to the rules
          <rules>
          `cat pyguide.md`
          </rules>

          If you think the code below conforms to the rules, output 'OK' with nothing else.
          Otherwise, for each rule in rules (from 2.1 onwards), analyze the code and provide feedback in the following format:
          Rule <number>: <rule name>
          Original:
          \`\`\`python
          problematic code here
          \`\`\`
          Suggestion:
          \`\`\`python
          improved code here
          \`\`\`

          <code>
          `cat tutorial/spiders/bug.py`
          </code>
          "

          output=$(./defect --schema=bedrock --model=us.anthropic.claude-3-5-sonnet-20241022-v2:0 "$prompt")

          if [ "$output" != "OK" ]; then
            echo "$output"

            commit=$(git rev-parse HEAD)
            escaped_output=$(jq -n --arg val "$output" '$val')

            metrics_prompt="
            Below is a code review feedback,
            tell me how many suggestions are there.
            You should output a JSON object with the following format:

            <format>
            {"suggestions": 123}
            </format>

            You should only output the JSON object with nothing else.

            <feedback>
            $output
            </feedback>
            "
            metrics=$(./defect --schema=bedrock --model=us.anthropic.claude-3-5-sonnet-20241022-v2:0 "$metrics_prompt")
            timestamp=$(date +%s)
            echo "$metrics" > $timestamp.json
            date=$(date +'%Y/%m/%d')
            author=$(git log -1 --pretty=format:'%an')
            aws s3 cp $timestamp.json "s3://$BUCKET_AND_PREFIX/$date/$author/$timestamp.json"

            exit 1
          fi
        env:
          BUCKET_AND_PREFIX: "yannanab2"
